name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            binary: sbc_exporter-linux-amd64
          - os: linux
            arch: arm64
            binary: sbc_exporter-linux-arm64
          - os: darwin
            arch: amd64
            binary: sbc_exporter-darwin-amd64
          - os: darwin
            arch: arm64
            binary: sbc_exporter-darwin-arm64

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'
          cache: true

      - name: Build Binary
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -ldflags="-s -w -X main.version=${GITHUB_REF_NAME}" -o ${{ matrix.binary }} .
          chmod +x ${{ matrix.binary }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary }}
          path: ${{ matrix.binary }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
          generate_release_notes: true
